spring.application.name=MONETIQ
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/monetiq
spring.datasource.username=ksenija
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.h2.console.enabled=false

spring.mongodb.uri=mongodb+srv://ksenijarakovic_db_user:GFg0EY9pKu0b0wBS@cluster0.8nkwitu.mongodb.net/monetiq_ai
spring.mongodb.database=monetiq_ai

spring.data.redis.host=localhost
spring.data.redis.port=6379
